---

- name: Add FlatHub repository
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: system

- name: Instal Flatpak - Spotify
  flatpak:
    name: com.spotify.Client
    state: present

- name: Instal Flatpak - Atom
  flatpak:
    name: io.atom.Atom
    state: present

- name: Instal Flatpak - Flatseal
  flatpak:
    name: com.github.tchx84.Flatseal
    state: present
