---

- name: Update all installed packages
  dnf:
    name: "*"
    state: latest
    update_cache: yes

- name: Install packages - Multimedia
  dnf:
    name:
      - vlc
    state: latest

- name: Install packages - Web
  dnf:
    name:
      - firefox
      - filezilla
      - chromium-freeworld
      #- google-chrome-stable  # Replaced by Chromium - REMOVELATER
      #- chrome-gnome-shell    # Replaced by Chromium - REMOVELATER

- name: Install packages - Graphics
  dnf:
    name:
      - darktable
      - inkscape
      - gimp
      - gthumb
      - ImageMagick

- name: Install packages - Work
  dnf:
    name:
      - git
      - vim
      - gvim
      - meld
      - virtualenv
      - python3-virtualenvwrapper
      - jq
      - ipython
      - krb5-workstation
      - pylint
      - python3-pyflakes
      - black
      - ctags

- name: Install packages - Look
  dnf:
    name:
      - arc-theme
      - numix-icon-theme-circle

- name: Install packages - Misc
  dnf:
    name:
      - mc
      - dropbox
      - calibre
      - menulibre
      - mono-core
      - htop
      - gnome-tweaks
      - unrar
      - rpmconf
      - dnf-plugin-system-upgrade
      - podman
      - flatpak
      - gnome-terminal-nautilus
      - libreoffice-langpack-cs
      - keepass
      - mediawriter

- name: Install packages - Video acceleration for Intel
  block:
    - dnf:
        name:
          - intel-media-driver # New generation of Intel Graphic cards
          - libva
          - libva-intel-driver # Pre Broadwell generation of Intel Graphic cards
          #- libva-vdpau-driver # Nvidia
          - libva-utils
    - debug:
        msg: "See more: https://lukas.zapletalovi.com/2020/10/enable-vaapi-on-intel.html"

- name: Install packages - Virtualization
  dnf:
    name:
      - virtualbox
      - kernel-devel
  when: complete | default(False)

- name: Install packages - Networking
  dnf:
    name:
      - nmap
      - wireshark
      - wireshark-cli
  when: complete | default(False)

- name: Install packages - Video editing
  dnf:
    name:
      - shotcut
  when: complete | default(False)

- name: Install packages - Software Defined Radio (SDR)
  dnf:
    name:
      - rtl-sdr
      - gqrx
      - gnuradio
  when: complete | default(False)

- name: Install packages - Machine Learning
  dnf:
    name:
      - python3-scikit-learn
      - python3-jupyter-client
      - python3-jupyter-core
  when: complete | default(False)

- name: Install packages - Cloud
  dnf:
    name:
      - awscli
  when: complete | default(False)

- name: Install packages - Games
  dnf:
    name:
      - wesnoth
      - openttd
      - steam
  when: complete | default(False)
