---

- name: Repositories - RPM Fusion GPG keys
  rpm_key:
    state: present
    key: "{{ item }}"
  loop:
    - 'https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-{{ansible_distribution|lower}}-2020'
    - 'https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-{{ansible_distribution|lower}}-2020'

- name: Repositories - RPM Fusion
  dnf:
    name:
      - 'https://download1.rpmfusion.org/free/{{ansible_distribution|lower}}/rpmfusion-free-release-{{ansible_distribution_version}}.noarch.rpm'
      - 'https://download1.rpmfusion.org/nonfree/{{ansible_distribution|lower}}/rpmfusion-nonfree-release-{{ansible_distribution_version}}.noarch.rpm'
    state: present

- name: Repositories - Repofiles
  copy:
    src: "{{ item }}"
    dest: /etc/yum.repos.d/
    owner: root
    group: root
    mode: 0644
    seuser: "system_u"
    setype: "system_conf_t"
  loop:
    #- "dropbox.repo" # Dropbox is included in RPM Fusion now REMOVELATER
    - "google-chrome.repo"
    - "virtualbox.repo"
