---

- name: Repositories - RPM Fusion
  dnf:
    name:
      - 'https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_version}}.noarch.rpm'
      - 'https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_version}}.noarch.rpm'
    state: present

- name: Repositories - Repofiles
  copy:
    src: "{{ item }}"
    dest: /etc/yum.repos.d/
    owner: root
    group: root
    mode: 0644
    seuser: "system_u"
    setype: "system_conf_t"
  loop:
    #- "dropbox.repo" # Dropbox is included in RPM Fusion now REMOVELATER
    - "google-chrome.repo"
    - "virtualbox.repo"
